### ISSUE TITLE
Management interface tracking issue

### ISSUE THREAD

**Issue by MTRNord** [MTRNord/erooster#6]
# Stage 1

- Build a cli
  - [ ] Allow creation of users 
  - [ ] Allow deletion of users
  - [ ] Allow changing passwords
    - [ ] Allow changing passwords in already bcrypt hashed form so that the admin doesn't know the password 
  - [ ] Allow creation of aliases
  - [ ] Allow removal of aliases 
  - [ ] Allow moving aliases

# Stage 2

- Build a Web interface
- Port same features as cli has
- Allow multiple domains
- Allow dkim relevant things to be set up (see mailu)
- Allow users to change their own passwords. 

Reference: mailu and mailcow.
